version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test1'
      #MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '123123'
    ports:
      - "3306:3306"  # 將 MySQL 的端口映射到宿主機的3306端口
